### ISSUE TITLE
Image weights are not considered while caching

### ISSUE THREAD

**Issue by lekhajee** [rackerlabs/arsenal#62]
Images with higher weights should be cached the most compared to images with lower weights.

**Comment by ClifHouck** [comment]
I think there's a problem with how dictionaries are being consumed by oslo config, or I just don't understand how to use dictionary options with oslo config. The strategy code appears to be good by proxy of the unit tests. Going to try to find a work-around to config issue.

**Comment by ClifHouck** [comment]
Comment above also applies to #61
